name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        rust: [1.69.0, nightly]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install ${{ matrix.rust }} --profile minimal && rustup default ${{ matrix.rust }}
      - run: cargo test --workspace --all-features

  clippy:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Default to latest stable as installed on the runners.
      # This does mean there may be updates that break this job at some point.
      - run: cargo fmt --all -- --check
      - run: cargo clippy --workspace --all-targets --all-features -- -D warnings
